"""
Teacher governance utilities.

The teacher role is responsible for reviewing plans generated by the agent and
providing feedback when the agent becomes stuck in a loop or produces unsafe
actions.  In this MVP the teacher logic is minimal; it constructs a payload
containing context about saturated task families and recent tasks.
"""

from __future__ import annotations

from typing import Dict, List

from igris.core import anti_loop


def build_teacher_payload(tasks: List[str], threshold: int = 3) -> Dict[str, object]:
    """Assemble a payload summarising the state for the teacher.

    The payload includes the list of saturated families and the recent tasks.
    """
    counts = anti_loop.compute_family_counts(tasks)
    saturated = anti_loop.saturated_families(counts, threshold=threshold)
    return {
        "recent_tasks": tasks[-20:],
        "saturated_families": saturated,
        "family_counts": counts,
    }